### ISSUE TITLE
Unable to detect player on WNYC

### ISSUE THREAD

**Issue by paulschreiber** [smatric/Playback-Rate-Controller#2]
Sample URL
https://www.wnyc.org/story/the-brian-lehrer-show-2020-07-10

![image](https://user-images.githubusercontent.com/86784/87179193-5685e380-c2ac-11ea-83eb-9a9d6a7963ca.png)

**Comment by paulschreiber** [comment]
Similar problem on https://www.spreaker.com/user/twobroadstalkingpolitics/assherises

**Comment by smatric** [comment]
The extension won't work on websites that initiate playback from JavaScript. Only those that use `<audio>` or `<video>` tags are supported.

Unfortunately, there doesn't seem to be a way to capture audio input without access to the original JS objects.
